module.exports = [
    {block: 'btn', content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'secondary'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'light'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'link'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'success'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'info'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'danger'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'warning'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'dark'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-primary'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-secondary'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-light'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-dark'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-success'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-info'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-danger'}, content: 'Текст кнопки'},
    {block: 'btn', mods: {styled: 'outline-warning'}, content: 'Текст кнопки'},
];