module.exports = [
    {block: 'btn', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-secondary', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-light', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-link', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-success', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-info', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-danger', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-warning', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-dark', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-primary', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-secondary', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-light', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-dark', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-success', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-info', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-danger', content: 'Текст кнопки'},
    {block: 'btn', cls: 'btn-outline-warning', content: 'Текст кнопки'},
];